# **Project: Music of Big Cities**

**Comparison of Moscow and St. Petersburg** is surrounded by myths. For example:
* Moscow is a metropolis, driven by the strict rhythm of the workweek.
* St. Petersburg is the cultural capital, with its own unique tastes.

Using Yandex.Music data, you will compare the behavior of users in these two major cities.

**Research Goal**  
Check three hypotheses:
1. User activity depends on the day of the week and manifests differently in Moscow and St. Petersburg.  
2. On Monday mornings in Moscow, certain genres dominate, while in St. Petersburg, different genres prevail. The same applies on Friday evenings—different genres dominate depending on the city.  
3. Moscow and St. Petersburg prefer different music genres. In Moscow, pop music is more popular, while in St. Petersburg, Russian rap prevails.

**Research Process**

You will use user behavior data from the file `yandex_music_project.csv`. Nothing is known about the data quality. Therefore, before testing these hypotheses, you will need to review the data.

You will check the data for errors and assess how they affect the study. Then, at the preprocessing stage, you will look for ways to correct the most critical data issues.

Thus, the study will include three stages:  
1. Data overview.  
2. Data preprocessing.  
3. Hypothesis testing.

## Data Overview

Develop an initial understanding of the Yandex.Music data.

**Task 1**

In [1]:
# import the pandas library
import pandas as pd

**Task 2**

In [2]:
# reading the data file and saving it in a DataFrame
df = pd.read_csv('/datasets/yandex_music_project.csv')

**Task 3**

In [3]:
# get the first 10 rows of the DataFrame df
df.head(10)

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday
5,842029A1,Преданная,IMPERVTOR,rusrap,Saint-Petersburg,13:09:41,Friday
6,4CB90AA5,True,Roman Messer,dance,Moscow,13:00:07,Wednesday
7,F03E1C1F,Feeling This Way,Polina Griffith,dance,Moscow,20:47:49,Wednesday
8,8FA1D3BE,И вновь продолжается бой,NaN,ruspop,Moscow,09:17:40,Friday
9,E772D5C0,Pessimist,NaN,dance,Saint-Petersburg,21:20:49,Wednesday

**Task 4**

In [4]:
# get overall information about the data in the DataFrame df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65079 entries, 0 to 65078
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0     userID  65079 non-null  object
 1   Track     63848 non-null  object
 2   artist    57876 non-null  object
 3   genre     63881 non-null  object
 4     City    65079 non-null  object
 5   time      65079 non-null  object
 6   Day       65079 non-null  object
dtypes: object(7)
memory usage: 3.5+ MB

The number of values in the columns differs. This means that there are missing values in the data.

**Task 5**

In [1]:
# Write your answer here as a comment. Do not remove the '#' symbol. Do not change the cell type to Markdown.
# From the column name 'time', it's not entirely clear what data is stored there. It might represent the listening time,
# or it might indicate the time when the track was listened to.

**Conclusions**

Each row of the table contains data about a listened track. Some columns describe the track itself: title, artist, and genre. The remaining data provide information about the user: which city they are from and when they listened to music.

It can be preliminarily stated that the data is sufficient to test the hypotheses. However, there are missing values, and the column names do not adhere to best practices.

To proceed further, the data issues need to be resolved.

## Data Preprocessing

### Column Renaming

**Task 6**

In [8]:
# list of column names in the DataFrame df
df.columns

Index(['  userID', 'Track', 'artist', 'genre', '  City  ', 'time', 'Day'], dtype='object')

**Task 7**

In [11]:
# renaming columns
df = df.rename(columns={'  userID': 'user_id', 'Track': 'track', '  City  ': 'city', 'Day': 'day'})

**Task 8**

In [13]:
# check the results - list of column names
df.columns

Index(['user_id', 'track', 'artist', 'genre', 'city', 'time', 'day'], dtype='object')

### Handling Missing Values

**Task 9**

In [14]:
# count missing values
df.isna().sum()

user_id       0
track      1231
artist     7203
genre      1198
city          0
time          0
day           0
dtype: int64

**Task 10**

In [16]:
# replacing missing values with 'unknown'
columns_to_replace = ['track', 'artist', 'genre']
for col in columns_to_replace:
    df[col] = df[col].fillna('unknown')

**Task 11**

In [17]:
# check for missing passes
df.isna().sum()

user_id    0
track      0
artist     0
genre      0
city       0
time       0
day        0
dtype: int64

### Duplicate Handling

**Task 12**

In [19]:
# counting obvious duplicates
df.duplicated().sum()

3826

**Task 13**

In [20]:
# removing explicit duplicates, creating new indices, and dropping the old ones
df = df.drop_duplicates().reset_index(drop=True)

**Task 14**

In [21]:
# checking for the absence of explicit duplicates
df.duplicated().sum()

0

**Task 15**

In [25]:
# view sorted unique genre names
df['genre'].sort_values().unique()

array(['acid', 'acoustic', 'action', 'adult', 'africa', 'afrikaans',
       'alternative', 'alternativepunk', 'ambient', 'americana',
       'animated', 'anime', 'arabesk', 'arabic', 'arena',
       'argentinetango', 'art', 'audiobook', 'author', 'avantgarde',
       'axé', 'baile', 'balkan', 'beats', 'bigroom', 'black', 'bluegrass',
       'blues', 'bollywood', 'bossa', 'brazilian', 'breakbeat', 'breaks',
       'broadway', 'cantautori', 'cantopop', 'canzone', 'caribbean',
       'caucasian', 'celtic', 'chamber', 'chanson', 'children', 'chill',
       'chinese', 'choral', 'christian', 'christmas', 'classical',
       'classicmetal', 'club', 'colombian', 'comedy', 'conjazz',
       'contemporary', 'country', 'cuban', 'dance', 'dancehall',
       'dancepop', 'dark', 'death', 'deep', 'deutschrock', 'deutschspr',
       'dirty', 'disco', 'dnb', 'documentary', 'downbeat', 'downtempo',
       'drum', 'dub', 'dubstep', 'eastern', 'easy', 'electronic',
       'electropop', 'emo', 'entehno', 'epicmetal', 'estrada', 'ethnic',
       'eurofolk', 'european', 'experimental', 'extrememetal', 'fado',
       'fairytail', 'film', 'fitness', 'flamenco', 'folk', 'folklore',
       'folkmetal', 'folkrock', 'folktronica', 'forró', 'frankreich',
       'französisch', 'french', 'funk', 'future', 'gangsta', 'garage',
       'german', 'ghazal', 'gitarre', 'glitch', 'gospel', 'gothic',
       'grime', 'grunge', 'gypsy', 'handsup', "hard'n'heavy", 'hardcore',
       'hardstyle', 'hardtechno', 'hip', 'hip-hop', 'hiphop',
       'historisch', 'holiday', 'hop', 'horror', 'house', 'hymn', 'idm',
       'independent', 'indian', 'indie', 'indipop', 'industrial',
       'inspirational', 'instrumental', 'international', 'irish', 'jam',
       'japanese', 'jazz', 'jewish', 'jpop', 'jungle', 'k-pop',
       'karadeniz', 'karaoke', 'kayokyoku', 'korean', 'laiko', 'latin',
       'latino', 'leftfield', 'local', 'lounge', 'loungeelectronic',
       'lovers', 'malaysian', 'mandopop', 'marschmusik', 'meditative',
       'mediterranean', 'melodic', 'metal', 'metalcore', 'mexican',
       'middle', 'minimal', 'miscellaneous', 'modern', 'mood', 'mpb',
       'muslim', 'native', 'neoklassik', 'neue', 'new', 'newage',
       'newwave', 'nu', 'nujazz', 'numetal', 'oceania', 'old', 'opera',
       'orchestral', 'other', 'piano', 'podcasts', 'pop', 'popdance',
       'popelectronic', 'popeurodance', 'poprussian', 'post',
       'posthardcore', 'postrock', 'power', 'progmetal', 'progressive',
       'psychedelic', 'punjabi', 'punk', 'quebecois', 'ragga', 'ram',
       'rancheras', 'rap', 'rave', 'reggae', 'reggaeton', 'regional',
       'relax', 'religious', 'retro', 'rhythm', 'rnb', 'rnr', 'rock',
       'rockabilly', 'rockalternative', 'rockindie', 'rockother',
       'romance', 'roots', 'ruspop', 'rusrap', 'rusrock', 'russian',
       'salsa', 'samba', 'scenic', 'schlager', 'self', 'sertanejo',
       'shanson', 'shoegazing', 'showtunes', 'singer', 'ska', 'skarock',
       'slow', 'smooth', 'soft', 'soul', 'soulful', 'sound', 'soundtrack',
       'southern', 'specialty', 'speech', 'spiritual', 'sport',
       'stonerrock', 'surf', 'swing', 'synthpop', 'synthrock',
       'sängerportrait', 'tango', 'tanzorchester', 'taraftar', 'tatar',
       'tech', 'techno', 'teen', 'thrash', 'top', 'traditional',
       'tradjazz', 'trance', 'tribal', 'trip', 'triphop', 'tropical',
       'türk', 'türkçe', 'ukrrock', 'unknown', 'urban', 'uzbek',
       'variété', 'vi', 'videogame', 'vocal', 'western', 'world',
       'worldbeat', 'ïîï', 'электроника'], dtype=object)

**Task 16**

In [26]:
# removing implicit duplicates 
duplicates = ['hip', 'hop', 'hip-hop']
name_genre = 'hiphop'
df['genre'] = df['genre'].replace(duplicates, name_genre)

**Task 17**

In [27]:
# checking for the absence of implicit duplicates
df['genre'].sort_values().unique()

array(['acid', 'acoustic', 'action', 'adult', 'africa', 'afrikaans',
       'alternative', 'alternativepunk', 'ambient', 'americana',
       'animated', 'anime', 'arabesk', 'arabic', 'arena',
       'argentinetango', 'art', 'audiobook', 'author', 'avantgarde',
       'axé', 'baile', 'balkan', 'beats', 'bigroom', 'black', 'bluegrass',
       'blues', 'bollywood', 'bossa', 'brazilian', 'breakbeat', 'breaks',
       'broadway', 'cantautori', 'cantopop', 'canzone', 'caribbean',
       'caucasian', 'celtic', 'chamber', 'chanson', 'children', 'chill',
       'chinese', 'choral', 'christian', 'christmas', 'classical',
       'classicmetal', 'club', 'colombian', 'comedy', 'conjazz',
       'contemporary', 'country', 'cuban', 'dance', 'dancehall',
       'dancepop', 'dark', 'death', 'deep', 'deutschrock', 'deutschspr',
       'dirty', 'disco', 'dnb', 'documentary', 'downbeat', 'downtempo',
       'drum', 'dub', 'dubstep', 'eastern', 'easy', 'electronic',
       'electropop', 'emo', 'entehno', 'epicmetal', 'estrada', 'ethnic',
       'eurofolk', 'european', 'experimental', 'extrememetal', 'fado',
       'fairytail', 'film', 'fitness', 'flamenco', 'folk', 'folklore',
       'folkmetal', 'folkrock', 'folktronica', 'forró', 'frankreich',
       'französisch', 'french', 'funk', 'future', 'gangsta', 'garage',
       'german', 'ghazal', 'gitarre', 'glitch', 'gospel', 'gothic',
       'grime', 'grunge', 'gypsy', 'handsup', "hard'n'heavy", 'hardcore',
       'hardstyle', 'hardtechno', 'hiphop', 'historisch', 'holiday',
       'horror', 'house', 'hymn', 'idm', 'independent', 'indian', 'indie',
       'indipop', 'industrial', 'inspirational', 'instrumental',
       'international', 'irish', 'jam', 'japanese', 'jazz', 'jewish',
       'jpop', 'jungle', 'k-pop', 'karadeniz', 'karaoke', 'kayokyoku',
       'korean', 'laiko', 'latin', 'latino', 'leftfield', 'local',
       'lounge', 'loungeelectronic', 'lovers', 'malaysian', 'mandopop',
       'marschmusik', 'meditative', 'mediterranean', 'melodic', 'metal',
       'metalcore', 'mexican', 'middle', 'minimal', 'miscellaneous',
       'modern', 'mood', 'mpb', 'muslim', 'native', 'neoklassik', 'neue',
       'new', 'newage', 'newwave', 'nu', 'nujazz', 'numetal', 'oceania',
       'old', 'opera', 'orchestral', 'other', 'piano', 'podcasts', 'pop',
       'popdance', 'popelectronic', 'popeurodance', 'poprussian', 'post',
       'posthardcore', 'postrock', 'power', 'progmetal', 'progressive',
       'psychedelic', 'punjabi', 'punk', 'quebecois', 'ragga', 'ram',
       'rancheras', 'rap', 'rave', 'reggae', 'reggaeton', 'regional',
       'relax', 'religious', 'retro', 'rhythm', 'rnb', 'rnr', 'rock',
       'rockabilly', 'rockalternative', 'rockindie', 'rockother',
       'romance', 'roots', 'ruspop', 'rusrap', 'rusrock', 'russian',
       'salsa', 'samba', 'scenic', 'schlager', 'self', 'sertanejo',
       'shanson', 'shoegazing', 'showtunes', 'singer', 'ska', 'skarock',
       'slow', 'smooth', 'soft', 'soul', 'soulful', 'sound', 'soundtrack',
       'southern', 'specialty', 'speech', 'spiritual', 'sport',
       'stonerrock', 'surf', 'swing', 'synthpop', 'synthrock',
       'sängerportrait', 'tango', 'tanzorchester', 'taraftar', 'tatar',
       'tech', 'techno', 'teen', 'thrash', 'top', 'traditional',
       'tradjazz', 'trance', 'tribal', 'trip', 'triphop', 'tropical',
       'türk', 'türkçe', 'ukrrock', 'unknown', 'urban', 'uzbek',
       'variété', 'vi', 'videogame', 'vocal', 'western', 'world',
       'worldbeat', 'ïîï', 'электроника'], dtype=object)

**Conclusions**

The data preprocessing revealed three issues:

- Inconsistencies in header style,
- Missing values,
- Duplicates — both explicit and implicit.

You corrected the headers to simplify working with the DataFrame. Without duplicates, the study will be more accurate.

Missing values were replaced with `'unknown'`. It still remains to be seen whether the missing values in the `genre` column will affect the study.

Now you can proceed to testing the hypotheses.

## Hypothesis Testing

### Comparison of the Behavior of Users in the Two Capitals

The first hypothesis states that users listen to music differently in Moscow and St. Petersburg. We will verify this assumption using data from three days of the week — Monday, Wednesday, and Friday. To do this:

* We will separate users from Moscow and St. Petersburg.
* We will compare the number of tracks listened to by each group on Monday, Wednesday, and Friday.

**Task 18**

In [30]:
# counting the number of listens in each city
df.groupby('city')['track'].count()

city
Moscow              42741
Saint-Petersburg    18512
Name: track, dtype: int64

**Task 19**

In [32]:
# Count the number of listens on each of the three days
df.groupby('day')['track'].count()

day
Friday       21840
Monday       21354
Wednesday    18059
Name: track, dtype: int64

**Task 20**

In [34]:
def number_tracks(day, city):
    track_list = df[df['day'] == day] # select only rows from df where the 'day' column equals the variable day
    track_list = track_list[track_list['city'] == city] # select only rows from track_list where the 'city' column equals the variable city
    track_list_count = track_list['user_id'].count() # call the method to count rows for track_list using the 'user_id' column
    return track_list_count # return the value of track_list_count from the function

**Task 21**

In [35]:
number_tracks('Monday', 'Moscow') # number of listens in Moscow on Mondays

15740

In [36]:
number_tracks('Monday', 'Saint-Petersburg') # number of listens in Saint-Petersburg on Mondays

5614

In [37]:
number_tracks('Wednesday', 'Moscow') # number of listens in Moscow on Wednesdays

11056

In [38]:
number_tracks('Wednesday', 'Saint-Petersburg') # number of listens in Saint-Petersburg on Wednesdays

7003

In [39]:
number_tracks('Friday', 'Moscow') # number of listens in Moscow on Fridays

15945

In [40]:
number_tracks('Friday', 'Saint-Petersburg') # number of listens in Saint-Petersburg on Fridays

5895

**Task 22**

In [43]:
# creating a table with the results
# displaying the table on the screen
columns = ['city', 'monday', 'wednesday', 'friday']

info = pd.DataFrame(data=[['Moscow', 15740, 11056, 15945], ['Saint-Petersburg', 5614, 7003, 5895]], columns=columns)
info

               city  monday  wednesday  friday
0            Moscow   15740      11056   15945
1  Saint-Petersburg    5614       7003    5895

**Conclusions**

The data show a difference in user behavior:

- In Moscow, peak listening occurs on Monday and Friday, while there is a noticeable drop on Wednesday.
- In St. Petersburg, on the contrary, more music is listened to on Wednesdays. Activity on Monday and Friday is nearly equal and lower than on Wednesday.

Thus, the data support the first hypothesis.

### Music at the Beginning and End of the Week

According to the second hypothesis, on Monday morning in Moscow one set of genres prevails, while in St. Petersburg different genres dominate. Similarly, on Friday evening, different genres prevail depending on the city.

**Task 23**

In [44]:
# obtaining the moscow_general table from those rows of df where the 'city' column equals 'Moscow'
moscow_general = df[df['city'] == 'Moscow']

In [45]:
# obtaining the moscow_general table from those rows of df where the 'city' column equals 'Saint-Petersburg'
spb_general = df[df['city'] == 'Saint-Petersburg']

**Task 24**

In [46]:
def genre_weekday(df, day, time1, time2):
    # sequential filtering
    # keep only the rows of df where the day equals day
    genre_df = df[df['day'] == day] 
    # keep only the rows of genre_df where the time is less than time2
    genre_df = genre_df[genre_df['time'] < time2]
    # keep only the rows of genre_df where the time is greater than time1
    genre_df = genre_df[genre_df['time'] > time1]
    # group the filtered DataFrame by the column with genre names,
    # take the 'genre' column and count the number of rows for each genre using the count() method
    genre_df_grouped = genre_df.groupby('genre')['genre'].count()
    # sort the result in descending order (so that the most popular genres appear at the beginning of the Series)
    genre_df_sorted = genre_df_grouped.sort_values(ascending=False)
    # return a Series with the top 10 most popular genres in the specified time interval for the given day
    return genre_df_sorted[:10]

**Task 25**

In [47]:
genre_weekday(moscow_general, 'Monday', '07:00', '11:00') # call the function for Monday morning in Moscow

genre
pop            781
dance          549
electronic     480
rock           474
hiphop         286
ruspop         186
world          181
rusrap         175
alternative    164
unknown        161
Name: genre, dtype: int64

In [48]:
genre_weekday(spb_general, 'Monday', '07:00', '11:00') # call the function for Monday morning in St. Petersburg

genre
pop            218
dance          182
rock           162
electronic     147
hiphop          80
ruspop          64
alternative     58
rusrap          55
jazz            44
classical       40
Name: genre, dtype: int64

In [49]:
genre_weekday(moscow_general, 'Friday', '17:00', '23:00') # call the function for Friday evening in Moscow

genre
pop            713
rock           517
dance          495
electronic     482
hiphop         273
world          208
ruspop         170
alternative    163
classical      163
rusrap         142
Name: genre, dtype: int64

In [50]:
genre_weekday(spb_general, 'Friday', '17:00', '23:00') # call the function for Friday evening in St. Petersburg

genre
pop            256
electronic     216
rock           216
dance          210
hiphop          97
alternative     63
jazz            61
classical       60
rusrap          59
world           54
Name: genre, dtype: int64

**Conclusions**

If we compare the top 10 genres on Monday morning, we can draw the following conclusions:

1. In Moscow and St. Petersburg, people listen to similar music. The only difference is that the Moscow ranking includes the "world" genre, while the St. Petersburg ranking includes jazz and classical music.

2. In Moscow, there were so many missing values that the value `'unknown'` ranked tenth among the most popular genres. This means that missing values occupy a significant share of the data and threaten the validity of the study.

Friday evening does not change this picture. Some genres move slightly up, others move down, but overall the top 10 remains the same.

Thus, the second hypothesis was only partially confirmed:
* Users listen to similar music at the beginning and end of the week.
* The difference between Moscow and St. Petersburg is not very pronounced. In Moscow, Russian pop music is listened to more frequently, while in St. Petersburg, jazz is more popular.

However, the missing values cast doubt on this result. In Moscow, there are so many missing values that the top 10 ranking could look different if the lost data on genres were available.

### Genre Preferences in Moscow and St. Petersburg

Hypothesis: St. Petersburg is the rap capital, where rap music is listened to more often than in Moscow, while Moscow, a city of contrasts, is predominantly into pop music.

**Task 26**

In [52]:
# in one line: group the moscow_general DataFrame by the 'genre' column, select the 'genre' column, count the number of 'genre' values using count(), save it in moscow_genres,
# then sort the resulting Series in descending order and save it back into moscow_genres
moscow_genres = moscow_general.groupby('genre')['genre'].count().sort_values(ascending=False)

**Task 27**

In [54]:
moscow_genres.head(10) # view the first 10 rows of moscow_genres

genre
pop            5892
dance          4435
rock           3965
electronic     3786
hiphop         2096
classical      1616
world          1432
alternative    1379
ruspop         1372
rusrap         1161
Name: genre, dtype: int64

**Task 28**

In [55]:
# in one line: group the spb_general DataFrame by the 'genre' column, select the 'genre' column, count the number of 'genre' values using count(), save it in spb_genres,
# then sort the resulting Series in descending order and save it back into spb_genres

spb_genres = spb_general.groupby('genre')['genre'].count().sort_values(ascending=False)

**Task 29**

In [56]:
spb_genres.head(10) # view the first 10 rows of spb_genres

genre
pop            2431
dance          1932
rock           1879
electronic     1736
hiphop          960
alternative     649
classical       646
rusrap          564
ruspop          538
world           515
Name: genre, dtype: int64

**Conclusions**

The hypothesis was partially confirmed:
* Pop music is the most popular genre in Moscow, as the hypothesis suggested. Moreover, a similar genre—Russian pop—is also present in the top 10 genres.
* Contrary to expectations, rap is equally popular in both Moscow and St. Petersburg.

## Research Results

You have tested three hypotheses and established the following:

1. The day of the week affects user activity in Moscow and St. Petersburg differently.  
   The first hypothesis was fully confirmed.

2. Musical preferences do not change significantly throughout the week—whether in Moscow or St. Petersburg. Slight differences are noticeable at the beginning of the week on Mondays:  
   * In Moscow, the "world" genre is listened to,  
   * In St. Petersburg, jazz and classical music are favored.  

   Thus, the second hypothesis was only partially confirmed. This result might have been different if not for the missing data.

3. Users in Moscow and St. Petersburg have more in common than differences in their tastes. Contrary to expectations, genre preferences in St. Petersburg resemble those in Moscow.  
   The third hypothesis was not confirmed. Even if differences in preferences exist, they are not apparent in the majority of users.

**In practice, studies include testing statistical hypotheses.**  
It is impossible to draw conclusions about all service users from a subset of data without employing statistical methods.  
Testing statistical hypotheses will reveal how reliable the findings are based on the available data.  
You will become acquainted with the methods of hypothesis testing in the following topics.